### ISSUE TITLE
SUMO interface wrong URLs in .snap nightly build

### ISSUE THREAD

**Issue by ThomasOliverKimble** [cyberbotics/webots#4730] opened 2022-06-22 15:32 UTC
**Describe the Bug**
When opening the 'projects/vehicle/highway' world on R2022b Nightly 20-06-2022 .snap package:
There seems to be a  problem with the URLs, we are combining local and github urls... Getting the following errors:

- ERROR: Could not open file: '/snap/webots/x1/usr/share/webots/https:/raw.githubusercontent.com/cyberbotics/webots/96decb2fc65a6d0917e1d3f34365d6e17c1600e3/projects/vehicles/protos/range_rover/RangeRoverSportSVRSimple.proto'.
- Error: wb_supervisor_field_get_mf_node() called with an out-of-bound index: 0 (should be between 0 and -1).

The controller crashes when a vehicle is spawned with the wrong url.

**Additional context**
R2022b Nightly 20-06-2022 .snap package

**Comment by stefaniapedrazzi** [comment] 2022-06-28 07:02
I have a similar issue on my development system with a custom project and a local PROTO file stored in the project's `protos` file and not declared as extern.
In my case it seems that the PROTO is not found in the list of local files but searched in the list of Webots nodes (this seems why the "raw.githubusercontent.com" URL is added to the path).

**Comment by ad-daniel** [comment] 2022-06-28 08:12
> In my case it seems that the PROTO is not found (even if it exists and there is no reason why it is not found) in the list of local files but searched in the list of Webots nodes (this seems why the "raw.githubusercontent.com" URL is added to the path).

If it isn't declared then it's normal it won't find it. Part of the reason for the introduction of the EXTERNPROTO is to avoid searching for it, the world should include information about its location. If you insert it using the GUI, it will add the entry on save. If you create the world on a text editor, it's up to the user to declare it.

Concerning the `raw.githubusercontent...`, it sounds like the backwards compatibility mechanism is kicking in. Is your world prior to R2022a and is your PROTO named the same as an official one? Those are the conditions for the mechanism to kick in (and it not being declared of course)

**Comment by omichel** [comment] 2022-06-28 08:18
I have a very similar problem when opening the `highway.wbt` world on Windows with a distribution created out of the current develop branch.
```
INFO: sumo_supervisor: Starting controller: python.exe -u sumo_supervisor.py --no-netconvert --max-vehicles=100 --enable-height --port=8873 --seed=1 --step=200 --radius=-1 --maximum-lateral-speed=2.5 --maximum-angular-speed=3 --lane-change-delay=3
INFO: autonomous_vehicle: Starting controller: C:\Users\Olivi\AppData\Local\Programs\Webots\projects\vehicles\controllers\autonomous_vehicle\autonomous_vehicle.exe
You can drive this car!
Select the 3D window and then use the cursor keys to:
[LEFT]/[RIGHT] - steer
[UP]/[DOWN] - accelerate/slow down
Connect to SUMO... This operation may take a few seconds.
ERROR: Could not open file: 'C:/Users/Olivi/AppData/Local/Programs/Webots/https:/raw.githubusercontent.com/cyberbotics/webots/2c6c09cd42d7856994e0087a8755168cb8571365/projects/vehicles/protos/toyota/ToyotaPriusSimple.proto'.
ERROR: Skipped unknown 'ToyotaPriusSimple' node or PROTO.
ERROR: Could not open file: 'C:/Users/Olivi/AppData/Local/Programs/Webots/https:/raw.githubusercontent.com/cyberbotics/webots/2c6c09cd42d7856994e0087a8755168cb8571365/projects/vehicles/protos/toyota/ToyotaPriusSimple.proto'.
Error: wb_supervisor_field_get_mf_node() called with an out-of-bound index: 0 (should be between 0 and -1).
Traceback (most recent call last):
  File "sumo_supervisor.py", line 215, in <module>
    controller.run(options.port, options.disableTrafficLights, directory,
  File "C:\Users\Olivi\AppData\Local\Programs\Webots\projects\default\controllers\sumo_supervisor\SumoSupervisor.py", line 547, in run
    self.get_vehicles_position(id, self.traci.vehicle.getSubscriptionResults(id),
  File "C:\Users\Olivi\AppData\Local\Programs\Webots\projects\default\controllers\sumo_supervisor\SumoSupervisor.py", line 215, in get_vehicles_position
    index = self.get_vehicle_index(id)
  File "C:\Users\Olivi\AppData\Local\Programs\Webots\projects\default\controllers\sumo_supervisor\SumoSupervisor.py", line 136, in get_vehicle_index
    self.generate_new_vehicle(vehicleClass)
  File "C:\Users\Olivi\AppData\Local\Programs\Webots\projects\default\controllers\sumo_supervisor\SumoSupervisor.py", line 103, in generate_new_vehicle
    self.vehicles[self.vehicleNumber] = Vehicle(self.getFromDef(defName))
  File "C:\Users\Olivi\AppData\Local\Programs\Webots\projects\default\controllers\sumo_supervisor\Objects.py", line 124, in __init__
    self.type = self.car_node.getTypeName()
AttributeError: 'NoneType' object has no attribute 'getTypeName'
WARNING: 'sumo_supervisor' controller exited with status: 1.
```

**Comment by ad-daniel** [comment] 2022-06-28 08:39
Since these are spawned PROTO and they are undeclared, it should not be possible to spawn them to begin with. The issue is that the string being imported is:
```
DEF SUMO_VEHICLE0 Solid {
  translation 10000 0 0.5
 children [
MercedesBenzSprinterSimple{
  translation -2.85 0 0
  color 0.43 0.11 0.1
  recognitionColors [ 0.43 0.11 0.1 ]
  }
 ]
}
```
and the check that should prevent the spawning of undeclared PROTO [here](https://github.com/cyberbotics/webots/blob/d2d6ec9552c7683a08557970eb990f6d516461aa/src/webots/nodes/utils/WbNodeOperations.cpp#L174-L181) is bypassed because the nodes list only includes the upper `Solid`, and not check is made for MercedesBenzSprinterSimple. I'll take care of fixing it.

**Comment by stefaniapedrazzi** [comment] 2022-06-29 07:47
My issue with local PROTOs is fixed, thank you!

Just a question:
currently the local PROTO is correctly loaded even if not declared as EXTERNPROTO in the world.
This could for example happen if a user modifies manually the WBT file.
However, after saving the world the EXTERNPROTO declaration for the local file is still not added to the world file.

Is it mandatory or is it accepted that local files are not declared as EXTERNPROTO?
Otherwise on save, Webots should automatically add the EXTERNPROTO declaration for the local file so that the saved WBT is correct.

**Comment by stefaniapedrazzi** [comment] 2022-06-29 07:50
Another question is:
is it the expected behavior that now Webots default PROTO definitions have higher priority at load if undeclared than local PROTO files defined in the project?
shouldn't Webots print at least a warning if a PROTO used in the world is not declared as EXTERNPROTO?

**Comment by omichel** [comment] 2022-06-29 08:00
In a R2022b world, all the PROTOs used in a world file should be declared as EXTERNPROTO.
For backwards compatibility, a R2022a (or older) world doesn't need to have its PROTOs declated as EXTERNPROTO.
However, when saving to the R2022b, all the PROTOs used in the world (plus possibly emphemeral PROTOs) should be listed in the EXTERNPROTO declarations.

**Comment by stefaniapedrazzi** [comment] 2022-06-29 08:06
Seems fine.
So we still have to impreove the Webots code and:
* add a warning if a PROTO is not declared as EXTERNPROTO as the Webots default could be wrongly loaded instead of a local one
* when resolving undeclared PROTO, the url has to be added to the internal list of extern proto so that the PROTO will be declared on save

**Comment by ad-daniel** [comment] 2022-06-29 08:09
Undeclared PROTO should indeed show a warning, I think it currently doesn't because the backwards compatibility mechanism kicks in too early since it has a known proto name, if it's a random proto it would fail.

Normally there shouldn't be a priority, what is declared must be what is used.

As to deal with undeclared PROTO it's an issue that was brought up before but I didn't get around to do it yet. Essentially if we allow for undeclared PROTO to be loaded, people won't do so. If it's undeclared AND the backwards mechanism doesn't apply AND it is available locally, technically we could load it but we agreed we shouldn't. Instead what we could do is either:
- load it but show an error message so that the use knows what was actually loaded (and add it on save accordingly)
- not load it, but show a warning that tells the user what to do: "PROTO XYZ is not declared, do so by adding "EXTERNPROTO "path" to the world file"

**Comment by omichel** [comment] 2022-06-29 08:19
I still prefer the latter, as many users don't care about warnings as long as it works, which is not a good practice, but unfortunately it happens quite often.

**Comment by stefaniapedrazzi** [comment] 2022-06-29 08:23
For >= R2022b worlds seems fine to not load the PROTO and print a warning.

**Comment by omichel** [comment] 2022-06-29 08:39
My issue reported here is fixed as well.
I am closing the issue.
Feel free to re-open if you believe something was not fully addressed.

**Closed by omichel** 2022-06-29 08:39 UTC
Labels: bug
