### ISSUE TITLE
Crashes involving (but unrelated to) PROTO files

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#3215] opened 2021-06-23 12:40 UTC
**Describe the Bug**
During the conversion of the Lua PROTO files, some crashes have been identified in some of them. As they're not regressions and that in all cases the PROTO loads fine at least once, it is unlikely that the problem is itself the PROTO file but rather something else.

Road-based PROTO:
~~- open `AddRoadLaneSegment.proto`~~
~~- attempt to delete a `RoadLine` from `lines`.~~
~~- webots freezes/crashes. Notice that doing so in the lowest level PROTO `Road.proto` appears to work fine, only in the derived ones the problem manifests. Might be related to the endless regeneration observed here #2994~~

`PipeBoundingObject.proto`: 
~~- create a world that uses it, for instance a solid with it.~~
~~- changing any of the parameters such as `radius` or `height` from the world file and reloading it works just fine.~~
~~- making the same changes from the interface makes it crash.~~

`SumoInterface.proto`:
- change the maximum number of vehicles to be smaller than the current number vehicles in the world, it crashes Webots.

**Comment by BenjaminDeleze** [comment] 2022-06-14 06:12
I could not reproduce the crash with `SumoInterface.proto` neither on master or develop.
It seems it has been fixed by another PR

**Closed** 2022-06-14 06:49 UTC
Labels: bug, crash
