### ISSUE TITLE
Webots 2020b, maxStop and minStop do not work.

### ISSUE THREAD

**Issue by OTT123** [cyberbotics/webots#6101] opened 2023-04-25 13:00 UTC
**Describe the Bug**
I use webots_ros to perform torque control on a robotic arm with six degrees of freedom.
 I set the position and speed of all joints to INF.
I added attributes to joint number five: minStop -2.8; maxStop 2.8. But when I applied a torque of -5Nm to joint 5, the value measured by the position sensor of joint 5 (-23.3) exceeded the minStop I set, and this value was incomprehensible. (Figure 1)

The setting of joint 5 is shown in Figure 2

**System**
 - Ubuntu 20.04; ros_noetic; webots 2020b

![2023-04-25_20-44](https://user-images.githubusercontent.com/99379651/234283044-4c3fc90a-b78f-4a02-8014-ae57086c7c77.png)
Figure 1
![2023-04-25_20-54](https://user-images.githubusercontent.com/99379651/234283065-6a0d593d-e2b7-4ad5-bb56-a190561ea956.png)
Figure 2 It can be found that the position goes beyond minStop

**Comment by ygoumaz** [comment] 2023-05-01 08:29
This is a known bug (see #3947). It probably has nothing to do with ROS, as the same problem can be reproduced with a classic controller. I will close this issue to avoid duplicates, but start investigating where the problem is coming from.

**Closed by ygoumaz** 2023-05-01 08:29 UTC
