### ISSUE TITLE
Enlarge IndexedLineSet display

### ISSUE THREAD

**Issue by ShuffleWire** [cyberbotics/webots#3395] opened 2021-07-12 09:02 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice if we could specify a width for graphical representation of IndexedLineSet, so that it's more easily visible.
Same thing for joint axis and so forth...
Also, it would be nice, imo, to increase the default "lineScale", as it's too small, and when a user toggle joint axis display on, nothing change, because lines are often too short.
Same thing goes for the Center of mass representation, lines are too light.
As a side note, changing the line color using a material doesn't seem reliable... (when I remove it, the color don't go back to the default)

**Describe the solution you'd like**
I currently have this : 
![image](https://user-images.githubusercontent.com/83014015/125259328-7f95e580-e2ff-11eb-9df2-17c577b061e3.png)
And I wish to be able to do something like this : 
![image](https://user-images.githubusercontent.com/83014015/125259859-06e35900-e300-11eb-90f6-47b70bbce574.png)
And maybe use color, but it's not a big deal
The solution would be to add a "width" field in the IndexedLineSet, and the same goes in the WorldInfo, when adding such sort of field next to lineScale would be nice.

**Describe alternatives you've considered**
Using indexed face set and draw big polygon manually, but it's not very handy.

**Comment by ShuffleWire** [comment] 2021-07-19 22:13
Just found out that it's a duplicate of #2512

**Comment by BenjaminDeleze** [comment] 2021-11-15 09:56
Close because duplicate of #2512

**Closed by BenjaminDeleze** 2021-11-15 09:56 UTC
Labels: enhancement
