### ISSUE TITLE
e-puck simulation on Webots.cloud

### ISSUE THREAD

**Issue by joachimhgg** [cyberbotics/webots#4307] opened 2022-03-03 09:20 UTC
**Description**

https://beta.webots.cloud/simulation return `Wrong folder name` when adding the e-puck's worlds:
for example: 
https://github.com/cyberbotics/webots/blob/R2021b/projects/robots/gctronic/e-puck/worlds/e-puck.wbt

It does not seem to depend of the branch, maybe the `-` of the folder e-puck ?

**Comment by omichel** [comment] 2022-03-07 10:12
@ThomasOliverKimble and @BenjaminDeleze: can we close this issue?

**Comment by BenjaminDeleze** [comment] 2022-03-07 10:15
No, the issue is not solved

**Comment by ThomasOliverKimble** [comment] 2022-04-07 08:20
It was indeed the `-` of the e-puck folder. This was fixed in PR [#3](https://github.com/cyberbotics/webots-cloud/pull/3) in `php/simulation.php`, folder names can now contain `-` in them.

We can see that it is working [here](https://beta.webots.cloud/run?url=https://github.com/ThomasOliverKimble/GuidedTour/blob/guided-tour/e-puck/worlds/e-puck_line_demo.wbt)

**Closed by ThomasOliverKimble** 2022-04-07 08:20 UTC
Labels: bug
