### ISSUE TITLE
Missing texture when importing VRML

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#3291] opened 2021-07-02 08:54 UTC
**Describe the Bug**
Although the texture `brushed_aluminium` is exported to the VRML, it isn't visible when importing it.

**Steps to Reproduce**
1. Create world
2. Add `TexturedBackground`, `TexturedBackgroundLight`, `RectangleArena`, `WoodenBox`, `OfficeChair`.
3. Save and export VRML.
4. Create new empty world and save it
5. Import the wrl. The legs of the office chair are white instead of silver.

**System**
 - Operating System: Windows 10

**Comment by BenjaminDeleze** [comment] 2021-07-06 10:15
The problem is caused by the fact that VRML does not support `PBRApperance`.
So during the export, the `PBRAppereance` is converted to a simple `Appearance`. So only the `base_color` image is exported. and that's why it seems "white" instead of silver: we are missing the normal, metalness, roughness,...

I will close this issue for now. Feel free to reopen it if there is a further problem.

**Closed by BenjaminDeleze** 2021-07-06 10:15 UTC
Labels: bug
