### ISSUE TITLE
webots.min.js: bounding box lines affected by post processing

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#754] opened 2019-07-25 10:06 UTC
The bounding box lines are not shown nicely on the scene in the three.js version because they are affected by the post processing effects.

Instead we should change the rendering order and render this kind of object at the very end so that they look clear.

![Screenshot from 2019-07-25 12-06-22](https://user-images.githubusercontent.com/5910449/61866003-a53c4100-aed4-11e9-92ba-cf991c08b5d0.png)

**Comment by stefaniapedrazzi** [comment] 2019-07-29 12:50
Given the new roadmap and that this could be a complex development, solving this issue is not a high-priority task.

**Comment by stefaniapedrazzi** [comment] 2019-07-29 14:38
Just note that this doesn't affect only the bounding boxes but all the lines, like the LineSet geometries

Web interface:
![Screenshot from 2019-07-29 16-36-15](https://user-images.githubusercontent.com/5910449/62057064-2a01c480-b21f-11e9-857d-fb502ee5d153.png)

Webots:
![geometric_primitives](https://user-images.githubusercontent.com/5910449/62057107-43a30c00-b21f-11e9-916e-3a8d5306ca87.png)

**Comment by fabienrohrer** [comment] 2019-07-29 14:42
I'm wondering if it's not an issue with your GPU, I cannot reproduce the bug:

<img width="611" alt="Capture d’écran 2019-07-29 à 16 41 31" src="https://user-images.githubusercontent.com/866788/62057362-d0e66080-b21f-11e9-9cc4-38cf9fcd68a3.png">

Did you tried to disable FXAA? It may alternate line rendering.

**Comment by stefaniapedrazzi** [comment] 2019-07-29 14:47
It is not the FXAA pass that causes issues but the hdrResolvePass.

**Comment by fabienrohrer** [comment] 2019-07-29 14:54
Good clue..

**Comment by stefaniapedrazzi** [comment] 2021-05-26 06:46
To be checked again on R2021b

**Comment by BenjaminDeleze** [comment] 2021-05-26 06:58
fixed in #2769

**Closed by BenjaminDeleze** 2021-05-26 06:58 UTC
Labels: wontfix
