### ISSUE TITLE
Lidar ranges (are again) not available after API restart

### ISSUE THREAD

**Issue by ShuffleWire** [cyberbotics/webots#5298] opened 2022-10-05 14:00 UTC
This bug came back in 2022b, it had been fixed before.
https://github.com/cyberbotics/webots/issues/3509

By the way, it's exactly the issue described here https://github.com/cyberbotics/webots/discussions/4154

note that even calling wb_supervisor_simulation_reset(); and the start of the controller don't change anything, even if I let the simulation run 1 step between reset and sensor setup.

after a look to the code, it's seems that the two lines in https://github.com/cyberbotics/webots/pull/3544/files#diff-b5827c7dc2bacb4ab37687df23574581283aec96cde3b9ac0143bd9e0d926b72 
have been forgotten...

**Comment by stefaniapedrazzi** [comment] 2022-10-06 08:43
I confirm the regression.
The connection to the extern controller code has been completely refactored and during the refactoring it seems that the code to support extern controller reconnection has been accidentally removed.
I will readd it and check that all the previously reported use cases are working again.

**Comment by ShuffleWire** [comment] 2022-10-06 09:34
the issue is actually caused by not calling wb_robot_cleanup() (when my controller crash, I've no way to execute it before it terminate)
If this function is called, everything work, and the next controller connection allows to continue the simulation from the point it left it, and lidar data are received.

**Comment by stefaniapedrazzi** [comment] 2022-10-06 10:34
It turns out that the extern controller is correctly reconnected (apart from an assertion failure raising in debug mode).
The problem is very specific to the lidar code and it is fixed in https://github.com/cyberbotics/webots/pull/5305.

**Closed** 2022-10-10 14:51 UTC
Labels: bug, regression
