### ISSUE TITLE
Weird behaviour in webots.min.js

### ISSUE THREAD

**Issue by michou214** [cyberbotics/webots#1191] opened 2019-12-13 09:45 UTC
**Describe the Bug**
The `webots.min.js` window that allows you to view a robot in its documentation page has some bugs in the rotation axes (the linear one tested were working fine). In addition, the button to reset the view and axes breaks all the robot configuration.
TIAGo base : wheels
TIAGo Iron : wheels, head and neck
TIAGo Steel : wheels, head, neck and arm
TIAGo Titanium: wheels, head, neck, arm, fingers
TIAGo++ : wheels, head, neck, arms, fingers

**Steps to Reproduce**
_Reset problem_
1. Go to 'https://cyberbotics.com/doc/guide/tiagopp?version=develop'
2. Click on `reset button`

_Rotational axis problem_
1. Go to 'https://cyberbotics.com/doc/guide/tiagopp?version=develop'
2. Move any `RotationalMotor` to see anormal behaviour

**Expected behavior**
The robot should have the same behaviour as in his world example that can be found at `WEBOTS_HOME/projects/robots/pal_robotics/tiago++/protos/Tiago++.proto`

**Screenshots**
_Reset problem_
Before clicking the button
![webots_min_js_reset_1](https://user-images.githubusercontent.com/36080014/70790244-f91cc900-1d94-11ea-8258-e2562e4f6925.png)

After clicking the button
![webots_min_js_reset_2](https://user-images.githubusercontent.com/36080014/70790245-f91cc900-1d94-11ea-836e-6582aa8bf38b.png)

_Axis problem_
![webots_min_js_axis](https://user-images.githubusercontent.com/36080014/70790243-f8843280-1d94-11ea-822b-c1407fa5588c.png)

**System**
 - Operating System: Linux Ubuntu 18.04.03 LTS
 - Graphics Card: GeForce GTX 1060 3GB/PCIe/SSE2

**Additional context**
I used the script provided to generate the files used for `webots.min.js`

**Comment by DavidMansolino** [comment] 2019-12-13 09:55
We should either fix this for the release either fallbck to the image temporarily as this gives a very bad user experience.

**Comment by DavidMansolino** [comment] 2019-12-13 14:54
Something is probably broken either on the generation side either on the web side (but for sure not in the robot model). I checked on a simple differential wheel robot and the problem is present too: https://www.cyberbotics.com/doc/guide/turtlebot3-burger?version=feature-turtelbot3

**Comment by fabienrohrer** [comment] 2019-12-16 07:58
Thank you for this report, I will check what is happening this morning.

**Comment by fabienrohrer** [comment] 2019-12-16 07:59
👀

**Comment by fabienrohrer** [comment] 2019-12-16 13:01
This comes from the fact that the Tiago and the TutleBot have rotated solids in their hinges. It's not the case from most of the other robots. This new case is simply not dealt in the robot components.

**Comment by fabienrohrer** [comment] 2019-12-16 15:25
Fixed in #1201

**Closed by fabienrohrer** 2019-12-16 15:25 UTC
Labels: bug
