### ISSUE TITLE
declare_externproto.py miss some declarations

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/webots#4959] opened 2022-07-26 13:21 UTC
When trying to convert `R2022a/projects/robots/festo/robotino3`, it misses the `SharpGP2Y0A41SK0F` proto.

When opening `robotino3.wbt`, I obtain the following warning: `ERROR: '/home/benjamin/Downloads/webots-R2022a-x86-64/webots/projects/robots/festo/robotino3/protos/Robotino3.proto':92:15: error: Skipped unknown 'SharpGP2Y0A41SK0F' node or PROTO.`

**Comment by ad-daniel** [comment] 2022-07-26 14:19
The issue is that in `robotino3.proto`, the PROTO `SharpGP2Y0A41SK0F` is defined as a string, not as a node per-se:
```
field  SFString{"SharpGP2D120", "SharpGP2Y0A41SK0F", "SharpGP2Y0A02YK0F"}  infraredSensorModel    "SharpGP2Y0A41SK0F"      # Extends the robot with infrared sensors.
```

since it doesn't follow the `<known-proto-name> {` (i.e, known name followed by open bracket) rule, the script doesn't create a declaration for it. I don't see an easy solution at the moment

**Comment by omichel** [comment] 2022-07-29 08:50
This is a very rare and special case which is not handled by the conversion script properly, but Webots provides a clear message on how to fix it. Fixing the conversion script in a generic way seems to be very complicated. Therefore I would suggest to close this issue as it won't cause important problems to the rare users who will bump into this special case.

**Closed by omichel** 2022-07-29 08:50 UTC
Labels: bug
