### ISSUE TITLE
Pioneer3Gripper falls apart when moving with a UR-5 robot

### ISSUE THREAD

**Issue by culurciello** [cyberbotics/webots#1963] opened 2020-07-22 13:12 UTC
Hi, I am using a Pioneer3Gripper with a UR-5 robot. As you can see from the image below, the gripper falls apart when the robot is moving moving. What would be the cause of this? If anyone can point me in the right direction I will try to fix the gripper PROTO file

![gripper_problem](https://user-images.githubusercontent.com/1007223/88180350-40a4e680-cbfb-11ea-9c27-5569321e8ea2.jpg)

Thanks a lot~
E

**Comment by DavidMansolino** [comment] 2020-07-23 10:04
Can you try with the `P-Grip` one (https://github.com/cyberbotics/webots/blob/develop/projects/robots/fp_robotics/p-rob3/protos/P-Grip.proto) to see if the problem is specific to this gripper?

**Comment by culurciello** [comment] 2020-07-23 17:35
Thanks @DavidMansolino this gripper does not have that problem == it stay in one piece during arm motion! Will test more now.

**Comment by DavidMansolino** [comment] 2020-07-24 06:37
Ok, good. 
About the original gripper, which gripper exactly are you using?
The one on the picture doesn't look like the `Khepera3_Gripper` one.

**Comment by DavidMansolino** [comment] 2020-07-24 06:42
Ok, good.
About the original gripper, to rotate the gripper, did you add an intermediate Transform or Solid node?

**Comment by omichel** [comment] 2020-11-30 10:11
I am closing this stalled issue. Feel free to re-open if needed.

**Closed by omichel** 2020-11-30 10:11 UTC
Labels: bug
