### ISSUE TITLE
ctrl+c/v does not work with other programs at first

### ISSUE THREAD

**Issue by Thomas-Feldmeier** [cyberbotics/webots#3475] opened 2021-07-20 08:50 UTC
ubuntu 20.04, webots 2021b
* reboot your system, start webots, open text editor with some file
* select a string from another program, press ctrl+C to copy it to the clipboard
* go to text file in webots, press there ctrl+v
* it should now paste the text into text editor, but nothing happens
* now copy and paste in webots text editor itself, it works
* now copy and paste from another program does work too, even if webots is closed and opened again

**Comment by stefaniapedrazzi** [comment] 2021-07-21 13:08
I tried with different systems and installation methods and I could not reproduce it: the text is copied the first time I press CTRL+V.
However, it happened once to me as well to have some issues with copy and paste.

**Comment by BenjaminDeleze** [comment] 2021-11-15 09:13
I'm closing this for now, feel free to reopen it if you have additional issues.

**Closed by BenjaminDeleze** 2021-11-15 09:13 UTC
Labels: bug, more information needed
