### ISSUE TITLE
Getting "squared" point clouds with 3d lidar.

### ISSUE THREAD

**Issue by francocipollone** [cyberbotics/webots#6505] opened 2024-02-19 17:28 UTC
**Describe the Bug**

When using lidar with a high amount of samples I get this squared format in the point cloud
![image](https://github.com/cyberbotics/webots/assets/53065142/01606bd0-4e0e-4fce-8074-3140333418c0)

**Steps to Reproduce**
1. Open 'Lidar' sample in webots
2. Modify Lidar specs using:
![image](https://github.com/cyberbotics/webots/assets/53065142/97080815-280c-4816-8e33-ac7995b14e53)
3. Enable point cloud visualization

**Expected behavior**
Point cloud should be computed correctly

**Screenshots**
![image](https://github.com/cyberbotics/webots/assets/53065142/01606bd0-4e0e-4fce-8074-3140333418c0)
![image](https://github.com/cyberbotics/webots/assets/53065142/6610223a-68ae-415f-953d-56c8337a3d29)

**System**
 - Operating System: Linux Ubuntu 20.04 & 22.04(docker)
 - R2023b Webots version installed from binaries.
 - Graphics Card: RTX 3050 ti Laptop

**Comment by francocipollone** [comment] 2024-02-20 14:29
![image](https://github.com/cyberbotics/webots/assets/53065142/a937764b-728b-408e-a00e-778fa7d392dd)

@ShuffleWire Thanks for quick reply!

**Comment by ShuffleWire** [comment] 2024-02-20 19:03
Got the same issue here...
Never used rotating lidar, so I can't really help...

**Comment by TonyWelte** [comment] 2024-03-17 10:24
I couldn't reproduce this on the master branch by manually compiling the project. Using the nightly builds versions 2023b-rev1 seem to work fine but version 2024a does appear to produce point could rotated by 180 degrees.

Looking at the diff between master and develop it appears there are some update introduced on develop
```
--- a/src/webots/nodes/WbLidar.cpp
+++ b/src/webots/nodes/WbLidar.cpp
@@ -362,7 +362,8 @@ void WbLidar::copyAllLayersToMemoryMappedFile() {
     maxWidth = ((double)w / 2.0) * (1.0 + ratio);
 
     double tmpAngle =
-      (fabs(mPreviousRotatingAngle / (2.0 * M_PI)) - floor(fabs(mPreviousRotatingAngle / (2.0 * M_PI)))) * (2.0 * M_PI);
+      (fabs((mPreviousRotatingAngle - M_PI) / (2.0 * M_PI)) - floor(fabs((mPreviousRotatingAngle - M_PI) / (2.0 * M_PI)))) *
+      (2.0 * M_PI);
     if (tmpAngle < 0)
       tmpAngle += 2.0 * M_PI;
     widthOffset = resolution * (tmpAngle / (2.0 * M_PI));
@@ -383,7 +384,7 @@ void WbLidar::copyAllLayersToMemoryMappedFile() {
         memcpy(data + (i + 1) * resolution + minWidth + widthOffset, mTemporaryImage + width() * (int)(i * skip) + minWidth,
                sizeof(float) * abs(minWidth + widthOffset));
         memcpy(data + i * resolution, mTemporaryImage + width() * (int)(i * skip) - widthOffset,
-               sizeof(float) * (maxWidth + widthOffset));
+               sizeof(float) * abs(maxWidth + widthOffset));
       }
     }
   }
```

These changes have been introduced by #6324. There must have been a conflict between the changes I made in #6417 and those of #6324, there is a missing `- M_PI` when `theta0` is computed for rotating lidars.

Note: The "tilt angle" can also produce point clouds slightly rotated #37

**Comment by ShuffleWire** [comment] 2024-03-19 10:13
That should be it ! Could you make a quick PR to fix that ?

**Comment by ShuffleWire** [comment] 2024-04-30 14:02
Closing because PR is merged

**Closed by ShuffleWire** 2024-04-30 14:02 UTC
